from enum import Enum


class FieldType(Enum):
    EDITABLE = 1
    DENORMALIZED = 2
    READ_ONLY = 3
    UNKNOWN = 4


class Families(Enum):
    TROOPS = 16
    CAPITAL_SHIPS = 20
    DEATH_STAR = 24
    FIGHTERS = 28
    ION_CANNONS = 34
    LASER_CANNONS = 35
    SHIELD_GENERATORS = 36
    DEATH_STAR_SHIELD_GENERATORS = 37
    ORBITAL_SHIPYARDS = 40
    TRAINING_FACILITIES = 41
    CONSTRUCTION_YARDS = 42
    MINES = 44
    REFINERIES = 45
    MON_MOTHMA = 48
    LEIA_ORGANA = 49
    LUKE_SKYWALKER = 50
    HAN_SOLO = 51
    EMPEROR_PALPATINE = 52
    DARTH_VADER = 53
    MINOR_CHARACTERS = 56
    SPECIAL_FORCES = 60
    SECTORS = 128
    CORE_SYSTEMS = 144
    OUTER_RIM_SYSTEMS = 146
